version: '3.8'
services: 
    mysql:
        image: "mysql:latest"
        container_name: mysql
        restart: always
        environment: 
            - MYSQL_ROOT_PASSWORD=mypassword
            - MYSQL_DATABASE=wildrydes
        ports:
            - "3306:3306"
    

    wildrydes:
        build: .
        image: "wildrydes:latest"
        container_name: wildrydes
        depends_on: 
            - mysql
        ports: 
            - "8080:8080"
